{{ if eq .ConfigItems.enable_ingress_template_controller "true"}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingresstemplates.zalando.org
spec:
  group: zalando.org
  version: v1
  scope: Namespaced
  names:
    kind: IngressTemplate
    singular: ingresstemplate
    plural: ingresstemplates
    shortNames:
    - it
    categories:
      - all
{{ end }}
